### ISSUE TITLE
[🐛Bug] The submit button doesnt redirect to a proper page

### ISSUE THREAD

**Issue by notvalproate** [Kunal-JockL/punarapi#10]
### Describe the bug

After submitting the form for requesting a sample, it redirects you to a page with only the response that was sent using res.send().

### Steps To Reproduce

1. Run the site on your local machine and open the website
2. Scroll down to the request sample form and fill it up
3. Submit the form
4. Observe no proper HTML template is loaded

### Expected Behavior

A request.ejs template to be created that shows the user whether the request was successfully sent or not.

### Screenshots

![image](https://github.com/Kunal-JockL/punarapi/assets/118114338/75d2e6d7-1b5f-4e76-b291-a3591d216d8b)

### Are you working on this issue?

Yes

**Comment by Kunal-JockL** [comment]
gooth
