### ISSUE TITLE
[✨Feature] create the contact us page.

### ISSUE THREAD

**Issue by Kunal-JockL** [Kunal-JockL/punarapi#14]
### Is your feature request related to a problem? Please describe

Develop a contact page for customers to input their details, which will be subsequently emailed to the owner. Additionally, send a formal "thank you" email to the potential customer.

### Describe the solution you'd like

Create a contact us page.

### Describe alternatives you've considered

None

### Are you working on this?

No

**Comment by notvalproate** [comment]
Can you assign me this issue?
