### ISSUE TITLE
[🐛Bug] Create a JS Function that changes the Radio buttons in Product-Page.

### ISSUE THREAD

**Issue by Kunal-JockL** [Kunal-JockL/punarapi#15]
### Describe the bug

On the product page, ensure that upon initial loading, the radio buttons are clearly visible by adjusting the color of the radio buttons to white in the section where they are located. Contrastingly, maintain a black background for the rest of the page. Additionally, in the footer, consider making the radio buttons either transparent or setting their display property to "none."

### Steps To Reproduce

Start off with reading the Functon that is there in product-radio.js .
create a function taking in the offset values of the introduction section and footer section to change color of radio buttons.

### Expected Behavior

Radio buttons should be visible.

### Screenshots

radio button not properly visible
![image](https://github.com/Kunal-JockL/punarapi/assets/109150464/04059e1e-b0a5-4de8-ada2-1bab40c98d15)
radio buttons covering map in footer
![image](https://github.com/Kunal-JockL/punarapi/assets/109150464/41adaa35-d3c4-4dc4-9eec-040698900aed)

### Are you working on this issue?

No

**Comment by notvalproate** [comment]
Can i work on this issue? i have a solution!

**Comment by Kunal-JockL** [comment]
hmm
