### ISSUE TITLE
[🐛Bug] Adjust the products section for mobile.

### ISSUE THREAD

**Issue by Kunal-JockL** [Kunal-JockL/punarapi#16]
### Describe the bug

The products section does not look good in mobile.

### Steps To Reproduce

go through the product section code, remember to disabe the hover function for phone and tablet.

### Expected Behavior

it should look gud on phone.

### Screenshots

How it currently looks on phone :
![image](https://github.com/Kunal-JockL/punarapi/assets/109150464/27093382-9337-4de4-8be3-c2b4702c5d92)
How it should look (Take insperation from here):
![image](https://github.com/Kunal-JockL/punarapi/assets/109150464/b4419280-5a07-42ff-bb18-26c25ba43490)

### Are you working on this issue?

Yes

**Comment by notvalproate** [comment]
I'd like to work on this issue!
