### ISSUE TITLE
[✨Feature] Add animation to the buttons in Quality section.

### ISSUE THREAD

**Issue by Kunal-JockL** [Kunal-JockL/punarapi#23]
### Is your feature request related to a problem? Please describe

You cannot see which button u clicked last so u dont know the content displayed is for which button. 
Here the content is for the color detailed button but theres no way of knowing.
![image](https://github.com/Kunal-JockL/punarapi/assets/109150464/8143d380-5f49-4e76-8dc3-6aaa0cfeefef)

### Describe the solution you'd like

Upon hovering over the buttons responsible for altering content in Quality-section (such as Sustainability, Color Detail, etc), an animated red line becomes activated. The objective is for this red line animation to persist beyond the button-click event and only dissipate when another button is subsequently clicked. also make sure that when the page is first rendered the first button i.e. sustainability is already clicked.

### Are you working on this?

No

**Comment by notvalproate** [comment]
I have a solution for this issue! can i get assigned?
