### ISSUE TITLE
[🐛Bug] Some Bugs in the navbar.

### ISSUE THREAD

**Issue by Kunal-JockL** [Kunal-JockL/punarapi#24]
### Describe the bug

1. The css hover effect is not removed for the navbar items on mobile
2. when the navbar is used to go to a different page and you click the back button on your phone to go to the last page the navbar is still open i.e. just the way you left it.

### Steps To Reproduce

1. Open the website on mobile.
2. Go to the product page by adding `/products` to the url
3. Open the navbar and click on any option, like product, or blog.
4. Notice that the hover effect is still there.
5. Press the back button on your mobile to return to the previous page.
6. Notice that the navbar is still open

### Expected Behavior

1. hover shouldnt work.
2. the navbar should always be closed when a new page is opened.

### Screenshots

Hover function working in moblie device.
![image](https://github.com/Kunal-JockL/punarapi/assets/109150464/6db79e10-5f21-48ea-8229-02521989ae84)

I used the navbar to go to the product section and then i clicked back button on my phone and came back to this.
![image](https://github.com/Kunal-JockL/punarapi/assets/109150464/57ff2460-7515-4002-b7ba-55a5cdee6b03)

I want it to come back to this.
![image](https://github.com/Kunal-JockL/punarapi/assets/109150464/102ec24d-9d1c-4d0a-8b9e-dffb560e1a13)

### Are you working on this issue?

No

**Comment by notvalproate** [comment]
I have the solution! can i make a PR?
