### ISSUE TITLE
[🐛Bug] The footer in the product page dosent show up.

### ISSUE THREAD

**Issue by Kunal-JockL** [Kunal-JockL/punarapi#7]
### Describe the bug

The footer section in the product page dosent show up even though the section is there in the html. the footer page for some reason showa up behind the products section.

### Steps To Reproduce

E.g.
2. Click on '...'
3. Scroll down to '...'
4. See Error

### Expected Behavior

footer page should show up

### Screenshots

The footer not there
![image](https://github.com/Kunal-JockL/punarapi/assets/109150464/f315dad3-bd5c-4067-8cdb-598e2afc550f)
The footer section here
![image](https://github.com/Kunal-JockL/punarapi/assets/109150464/e1211011-7349-4cf5-8c34-0b12d1c43a55)

### Are you working on this issue?

No

**Comment by notvalproate** [comment]
Happy to resolve this issue 😊
